name: PoorSpace
version: 1.2
main: com.gmail.jobstone.PoorSpace
description: A plugin.
author: Jobstone
api-version: 1.15
softdepend: [PoorMessage]
commands:
    poorspace:
        aliases: ps
        usage: /<command>
        permission: poorspace.basic
        permission-message: You don't have permission:<permission>
    ps-op:
        usage: /<command>
        permission: poorspace.op
        permission-message: You don't have permission:<permission>
permissions:
    poorspace.basic:
        description: Gives access.
        default: true
    poorspace.op:
        description: Gives op access.
        default: op